import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const supportedLanguages = [
  { code: 'en', native: 'English' },
  { code: 'te', native: 'తెలుగు' },
  { code: 'ta', native: 'தமிழ்' },
  { code: 'pa', native: 'ਪੰਜਾਬੀ' },
  { code: 'hi', native: 'हिन्दी' },
  { code: 'ml', native: 'മലയാളം' },
  { code: 'ur', native: 'اردو' },
  { code: 'ks', native: 'کٲشُر' },
  { code: 'kn', native: 'ಕನ್ನಡ' },
  { code: 'bn', native: 'বাংলা' },
  { code: 'or', native: 'ଓଡ଼ିଆ' },
  { code: 'mr', native: 'मराठी' },
  { code: 'gu', native: 'ગુજરાતી' }
];

const translations = {
  en: {
    navNearby: 'Nearby',
    navMap: 'Map',
    navSOS: 'SOS',
    navOffline: 'Offline',
    navProfile: 'Profile',
    navAdmin: 'Admin',
    emergencyHelpTitle: 'Emergency Help,\nRight When You Need It.',
    heroSubtitle: 'Instantly find nearby trauma centers, ambulances, police, and towing services with one tap.',
    getHelpNow: 'Get Help Now',
    whyTrustTitle: 'Why trust RoadSOS?',
    fastResponse: 'Fast Response',
    fastResponseDescription: 'Connects you directly to the closest available services.',
    verifiedContacts: 'Verified Contacts',
    verifiedContactsDescription: '100% verified emergency service numbers.',
    nearbyServices: 'Nearby Services',
    withinRadius: 'Within 50km radius',
    locatingYou: 'Locating you...',
    fetchingNearbyHelp: 'Fetching nearby help...',
    noServicesFound: 'No services found in this area.',
    all: 'All',
    hospital: 'Hospital',
    traumaCenter: 'Trauma Center',
    ambulance: 'Ambulance',
    policeStation: 'Police Station',
    towing: 'Towing',
    openNow: 'Open Now',
    closed: 'Closed',
    call: 'Call',
    navigate: 'Nav',
    emergency: 'EMERGENCY',
    tapButtonForAssistance: 'Tap the button for immediate assistance',
    sosActivatedAlert: 'SOS Activated! Sending your coordinates to nearest emergency center.',
    callNearestAmbulance: 'Call Nearest Ambulance',
    callPolice: 'Call Police',
    shareLocation: 'Share Location',
    contacts: 'Contacts',
    youAreHere: 'You are here',
    routePlotted: 'Route plotted!',
    emergencyProfile: 'Emergency Profile',
    edit: 'Edit',
    cancel: 'Cancel',
    save: 'Save',
    medicalNotes: 'Medical Notes',
    emergencyContacts: 'Emergency Contacts',
    bloodGroup: 'Blood Group:',
    noInternetTitle: 'No Internet Connection',
    noInternetText: 'Don\'t panic. You can still reach these nearby emergency contacts from your last known location.',
    nationalEmergencyNumbers: 'National Emergency Numbers',
    allEmergencies: 'All Emergencies',
    police: 'Police',
    ambulanceLabel: 'Ambulance',
    serviceManagement: 'Service Management',
    adminDescription: 'This dashboard allows system administrators to add, verify, and update emergency service locations in the database.',
    signInAsAdmin: 'Sign In as Admin',
    callService: 'Call',
    openNowStatus: 'Open Now',
    closedStatus: 'Closed',
    userProfileNamePlaceholder: 'Name',
    contactNamePlaceholder: 'Contact Name',
    phoneNumberPlaceholder: 'Phone Number',
  },
  te: {
    navNearby: 'ఉత్తర ప్రాంతాలు',
    navMap: 'నకము',
    navSOS: 'సోస్',
    navOffline: 'ఆఫ్‌లైన్',
    navProfile: 'ప్రొఫైల్',
    navAdmin: 'అడ్మిన్',
    emergencyHelpTitle: 'అత్యవసర సహాయం,\nమీకు అవసరం అయినప్పుడే.',
    heroSubtitle: 'ఒక ట్యాప్‌తో సమీప థ్రామా సెంటర్లు, యాంబులెన్సులు, పోలీస్ మరియు టోవింగ్ సేవలను వెంటనే కనుగొనండి.',
    getHelpNow: 'ఇప్పుడే సహాయం పొందండి',
    whyTrustTitle: 'RoadSOS మీద ఎందుకు నమ్మకం?',
    fastResponse: 'త్వరిత ప్రతిస్పందన',
    fastResponseDescription: 'మీకు దగ్గరలో ఉన్న సేవలను నేరుగా కలుపుతుంది.',
    verifiedContacts: 'తృటిహీన సమాచారాలు',
    verifiedContactsDescription: '100% ధృవీకరించిన అత్యవసర సేవాల సంఖ్యలు.',
    nearbyServices: 'సమీప సేవలు',
    withinRadius: '50 కి.మీ. పరిధిలో',
    locatingYou: 'మీని కనుగొంటున్నారు...',
    fetchingNearbyHelp: 'సమీప సహాయం పొందుతున్నాం...',
    noServicesFound: 'ఈ ప్రాంతంలో సేవలు కనుగొనబడలేదు.',
    all: 'అన్ని',
    hospital: 'హాస్పిటల్',
    traumaCenter: 'త్రావ్‌మా కేంద్రం',
    ambulance: 'ఆంబులెన్స్',
    policeStation: 'పోలీస్ స్టేషన్',
    towing: 'టోవింగ్',
    openNow: 'ఇప్పుడే తెరుచుకున్నది',
    closed: 'పెద్దది',
    call: 'కాల్ చేయండి',
    navigate: 'నావిగేట్',
    emergency: 'అత్యవసర',
    tapButtonForAssistance: 'త్వరిత సహాయానికి బటన్‌ను తట్టండి',
    sosActivatedAlert: 'SOS ప్రారంభించబడింది! మీ సమన్వయాలను సమీప అత్యవసర కేంద్రానికి పంపుతున్నాము.',
    callNearestAmbulance: 'సమీప ఆంబులెన్స్‌కి కాల్ చేయండి',
    callPolice: 'పోలిస్లకు కాల్ చేయండి',
    shareLocation: 'స్థానాన్ని పంచుకోండి',
    contacts: 'సంప్రదింపులు',
    youAreHere: 'మీరు ఇక్కడ ఉన్నారు',
    routePlotted: 'పథం చూపబడింది!',
    emergencyProfile: 'అత్యవసర ప్రొఫైల్',
    edit: 'మార్చు',
    cancel: 'రద్దు',
    save: 'రక్షించు',
    medicalNotes: 'వైద్య గమనికలు',
    emergencyContacts: 'అత్యవసర సంప్రదింపులు',
    bloodGroup: 'రక్త గ్రూపు:',
    noInternetTitle: 'ఇంటర్నెట్ కనెక్షన్ లేదు',
    noInternetText: 'ఆందోళన చెందకండి. మీరు ఇప్పటికైనా మీ చివరి తెలిసిన స్థానపు సమీప అత్యవసర సంప్రదింపులను చేరుకోవచ్చు.',
    nationalEmergencyNumbers: 'జాతీయ అత్యవసర నంబర్లు',
    allEmergencies: 'అన్ని అత్యవసరాలు',
    police: 'పోలీస్',
    ambulanceLabel: 'ఆంబులెన్స్',
    serviceManagement: 'సేవా నిర్వహణ',
    adminDescription: 'ఈ డ్యాష్‌బోర్డు సిస్టమ్ నిర్వాహకులను అత్యవసర సేవా స్థానాలను డేటాబేస్‌లో జోడించడానికి, ధృవీకరించడానికి మరియు నవీకరించడానికి అనుమతిస్తుంది.',
    signInAsAdmin: 'అడ్మిన్గా సైన్ ఇన్ చేయండి',
    callService: 'కాల్ చేయండి',
    openNowStatus: 'ఇప్పుడే తెరుచుకున్నది',
    closedStatus: 'పెద్దది',
    userProfileNamePlaceholder: 'పేరు',
    contactNamePlaceholder: 'సంప్రదింపు పేరు',
    phoneNumberPlaceholder: 'ఫోన్ నంబర్',
  },
  ta: {
    navNearby: 'பக்கத்திலுள்ளவை',
    navMap: 'நடு வரைபடம்',
    navSOS: 'SOS',
    navOffline: 'ஆஃப்லைன்',
    navProfile: 'சுயவிவரம்',
    navAdmin: 'நிர்வாகி',
    emergencyHelpTitle: 'அவசர உதவி,\nஉங்களுக்கு தேவையான பொழுது.',
    heroSubtitle: 'ஒரு தட்டுதலால் அருகிலுள்ள கவலைக்கிடமான மையங்கள், ஆம்புலன்ஸ்கள், காவல்துறை மற்றும் ரசவுது சேவைகளை உடனடியாக கண்டறியுங்கள்.',
    getHelpNow: 'தாமதமின்றி உதவி',
    whyTrustTitle: 'RoadSOS-ஐ ஏன் நம்பவேண்டும்?',
    fastResponse: 'வேகமான பதில்',
    fastResponseDescription: 'அறைபக்கமான சேவைகளை நேரடியாக உங்களிடம் கொண்டு சேர்க்கிறது.',
    verifiedContacts: 'உறுதிசெய்யப்பட்ட தொடர்புக்கள்',
    verifiedContactsDescription: '100% சரிபார்க்கப்பட்ட அவசர சேவை எண்கள்.',
    nearbyServices: 'சிக்கனமான சேவைகள்',
    withinRadius: '50கி.மீ. வரம்பில்',
    locatingYou: 'உங்களை கண்டறிகிறது...',
    fetchingNearbyHelp: 'அருகிலுள்ள உதவியைத் தேடுகிறது...',
    noServicesFound: 'இந்த பகுதியில் எந்த சேவையும் இல்லை.',
    all: 'அனைத்தும்',
    hospital: 'மருத்துவமனை',
    traumaCenter: 'அதிர்ச்சி மையம்',
    ambulance: 'ஆம்புலன்ஸ்',
    policeStation: 'காவல் நிலையம்',
    towing: 'டோயிங்',
    openNow: 'இப்பொழுது திறந்திருக்கும்',
    closed: 'மூடப்பட்டது',
    call: 'அழைக்க',
    navigate: 'வேறு',
    emergency: 'அவசரம்',
    tapButtonForAssistance: ' உடனடி உதவிக்கு பொத்தானை தட்டவும்',
    sosActivatedAlert: 'SOS செயல்படுத்தப்பட்டது! உங்கள் இடமாற்றங்களை அருகிலுள்ள அவசர மையத்திற்கு அனுப்புகிறது.',
    callNearestAmbulance: 'அருகிலுள்ள ஆம்புலன்ஸுக்கு அழைக்கவும்',
    callPolice: 'போலீசை அழைக்கவும்',
    shareLocation: 'இடத்தை பகிரவும்',
    contacts: 'தொடர்புகள்',
    youAreHere: 'நீங்கள் இங்கே இருக்கிறீர்கள்',
    routePlotted: 'மாறிவட்டம் வரைபடமிடப்பட்டது!',
    emergencyProfile: 'அவசர சுயவிவரம்',
    edit: 'தொகு',
    cancel: 'ரத்து',
    save: 'சேமி',
    medicalNotes: 'மருத்துவ குறிப்புகள்',
    emergencyContacts: 'அவசர தொடர்புகள்',
    bloodGroup: 'இரத்த வகை:',
    noInternetTitle: 'இணைய இணைப்பு இல்லை',
    noInternetText: 'கவலைப்பட வேண்டாம். உங்கள் கடைசியாக தெரிந்து கொண்ட இடத்தில் உள்ள அருகிலுள்ள அவசர தொடர்புகளை இன்னும் அணுகலாம்.',
    nationalEmergencyNumbers: 'தேசிய அவசர எண்கள்',
    allEmergencies: 'அனைத்து அவசரங்களும்',
    police: 'போலீஸ்',
    ambulanceLabel: 'ஆம்புலன்ஸ்',
    serviceManagement: 'சேவை மேம்பாடு',
    adminDescription: 'இந்த பலகை அமைப்பு நிர்வாகிகள் அவசர சேவை இடங்களை தரவுத்தளத்தில் சேர்க்க, சரிபார்க்க மற்றும் புதுப்பிக்க உதவுகிறது.',
    signInAsAdmin: 'நிர்வாகியாக உள்நுழையவும்',
    callService: 'அழைக்க',
    openNowStatus: 'இப்பொழுது திறந்திருக்கும்',
    closedStatus: 'மூடப்பட்டது',
    userProfileNamePlaceholder: 'பெயர்',
    contactNamePlaceholder: 'தொடர்பு பெயர்',
    phoneNumberPlaceholder: 'தொலைபேசி எண்',
  },
  pa: {
    navNearby: 'ਕੋਲ',
    navMap: 'ਨਕਸ਼ਾ',
    navSOS: 'SOS',
    navOffline: 'ਆਫਲਾਈਨ',
    navProfile: 'ਪ੍ਰੋਫਾਈਲ',
    navAdmin: 'ਐਡਮਿਨ',
    emergencyHelpTitle: 'ਐਮਰਜੈਂਸੀ ਸਹਾਇਤਾ,\nਜਦੋਂ ਤੁਹਾਨੂੰ ਲੋੜ ਹੋਵੇ.',
    heroSubtitle: 'ਇੱਕ ਟੈਪ ਨਾਲ ਨੇੜਲੇ ਥਰਾਮਾ ਸੈਂਟਰ, ਐਂਬੂਲੈਂਸ, ਪੁਲਿਸ ਅਤੇ ਟੋਇੰਗ ਸੇਵਾਵਾਂ ਤੁਰੰਤ ਲੱਭੋ.',
    getHelpNow: 'ਹੁਣ ਮਦਦ ਲਵੋ',
    whyTrustTitle: "RoadSOS 'ਤੇ ਕਿਉਂ ਭਰੋਸਾ?",
    fastResponse: 'ਤੇਜ਼ ਜਵਾਬ',
    fastResponseDescription: 'ਤੁਹਾਨੂੰ ਸਭ ਤੋਂ ਨੇੜਲੇ ਸੇਵਾਵਾਂ ਨਾਲ ਸਿੱਧਾ ਜੋੜਦਾ ਹੈ.',
    verifiedContacts: 'ਪੱਕੇ ਸੰਪਰਕ',
    verifiedContactsDescription: '100% ਪੱਕੇ ਐਮਰਜੈਂਸੀ ਸਰਵਿਸ ਨੰਬਰ.',
    nearbyServices: 'ਨਜ਼ਦੀਕੀ ਸੇਵਾਵਾਂ',
    withinRadius: '50 ਕਿ.ਮੀ. ਘੇਰੇ ਵਿੱਚ',
    locatingYou: 'ਤੁਹਾਨੂੰ ਲੱਭ ਰਿਹਾ ਹੈ...',
    fetchingNearbyHelp: 'ਨੇੜਲੇ ਮਦਦ ਲੱਭ ਰਹੀ ਹੈ...',
    noServicesFound: 'ਇਸ ਖੇਤਰ ਵਿੱਚ ਕੋਈ ਸੇਵਾਵਾਂ ਨਹੀਂ ਮਿਲੀਆਂ.',
    all: 'ਸਭ',
    hospital: 'ਹਸਪਤਾਲ',
    traumaCenter: 'ਟ੍ਰੌਮਾ ਸੈਂਟਰ',
    ambulance: 'ਐਮਬੂਲੈਂਸ',
    policeStation: 'ਪੁਲਿਸ ਸਟੇਸ਼ਨ',
    towing: 'ਟੋਇੰਗ',
    openNow: 'ਹੁਣ ਖੁੱਲਿਆ',
    closed: 'ਬੰਦ',
    call: 'ਕਾਲ ਕਰੋ',
    navigate: 'ਨੇਵੀਗੇਟ',
    emergency: 'ਐਮਰਜੈਂਸੀ',
    tapButtonForAssistance: 'ਤੁਰੰਤ ਸਹਾਇਤਾ ਲਈ ਬਟਨ ਦਬਾਓ',
    sosActivatedAlert: 'SOS ਚਾਲੂ ਹੋ ਗਿਆ! ਤੁਹਾਡੇ ਕੋਆਰਡੀਨੇਟ ਨੇੜਲੇ ਐਮਰਜੈਂਸੀ ਸੈਂਟਰ ਨੂੰ ਭੇਜੇ ਜਾ ਰਹੇ ਹਨ.',
    callNearestAmbulance: 'ਨੇੜਲੇ ਐਂਬੂਲੈਂਸ ਨੂੰ ਕਾਲ ਕਰੋ',
    callPolice: 'ਪੁਲਿਸ ਨੂੰ ਕਾਲ ਕਰੋ',
    shareLocation: 'ਟਿਕਾਣਾ ਸਾਂਝਾ ਕਰੋ',
    contacts: 'ਸੰਪਰਕ',
    youAreHere: 'ਤੁਸੀਂ ਇੱਥੇ ਹੋ',
    routePlotted: "ਰੂਟ ਨਕਸ਼ੇ 'ਤੇ ਦਰਸਾਇਆ ਗਿਆ!",
    emergencyProfile: 'ਐਮਰਜੈਂਸੀ ਪ੍ਰੋਫਾਈਲ',
    edit: 'ਸੰਪਾਦਿਤ ਕਰੋ',
    cancel: 'ਰੱਦ ਕਰੋ',
    save: 'ਸੰਭਾਲੋ',
    medicalNotes: 'ਚਿਕਿਤ्सा ਨੋਟਸ',
    emergencyContacts: 'ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ',
    bloodGroup: 'ਖੂਨ ਦਾ ਗਰੁੱਪ:',
    noInternetTitle: 'ਇੰਟਰਨੇਟ ਕਨੈਕਸ਼ਨ ਨਹੀਂ',
    noInternetText: 'ਚਿੰਤਾ ਨਾ ਕਰੋ. ਤੁਸੀਂ ਹਾਲੇ ਵੀ ਆਪਣੇ ਆਖਰੀ ਜਾਣੇ ਟਿਕਾਣੇ ਤੋਂ ਨੇੜਲੇ ਐਮਰਜੈਂਸੀ ਸੰਪਰਕਾਂ ਤੱਕ ਪਹੁੰਚ ਸਕਦੇ ਹੋ.',
    nationalEmergencyNumbers: 'ਅੰਤਰਰਾਸ਼ਟਰਿਆ ਐਮਰਜੈਂਸੀ ਨੰਬਰ',
    allEmergencies: 'ਸਭ ਐਮਰਜੈਂਸੀ',
    police: 'ਪੁਲਿਸ',
    ambulanceLabel: 'ਐਂਬੂਲੈਂਸ',
    serviceManagement: 'ਸੇਵਾ ਪ੍ਰਬੰਧਨ',
    adminDescription: 'ਇਹ ਡੈਸ਼ਬੋਰਡ ਸਿਸਟਮ ਪ੍ਰਸ਼ਾਸਕਾਂ ਨੂੰ ਐਮਰਜੈਂਸੀ ਸੇਵਾ ਸਥਾਨਾਂ ਨੂੰ ਡാറ്റਾਬੇਸ ਵਿੱਚ ਜੋੜਨ, ਪ੍ਰਮਾਣਿਤ ਕਰਨ ਅਤੇ ਅਪਡੇਟ ਕਰਨ ਦੀ ਆਗਿਆ ਦਿੰਦਾ ਹੈ.',
    signInAsAdmin: 'ਐਡਮਿਨ ਵਜੋਂ ਸਾਈਨ ਇਨ ਕਰੋ',
    callService: 'ਕਾਲ ਕਰੋ',
    openNowStatus: 'ਹੁਣ ਖੁੱਲਿਆ',
    closedStatus: 'ਬੰਦ',
    userProfileNamePlaceholder: 'ਨਾਮ',
    contactNamePlaceholder: 'ਸੰਪਰਕ ਨਾਮ',
    phoneNumberPlaceholder: 'ਫੋਨ ਨੰਬਰ',
  },
  hi: {
    navNearby: 'क़रीब',
    navMap: 'नक्शा',
    navSOS: 'एसओएस',
    navOffline: 'ऑफ़लाइन',
    navProfile: 'प्रोफ़ाइल',
    navAdmin: 'एडमिन',
    emergencyHelpTitle: 'आपातकालीन सहायता,\nजब भी आपको इसकी ज़रूरत हो।',
    heroSubtitle: 'एक टैप में निकटतम ट्रॉमा केंद्र, एम्बुलेंस, पुलिस और टोइंग सेवाएं तुरंत खोजें।',
    getHelpNow: 'अभी मदद लें',
    whyTrustTitle: 'RoadSOS पर क्यों भरोसा?',
    fastResponse: 'तेज़ प्रतिक्रिया',
    fastResponseDescription: 'आपको निकटतम उपलब्ध सेवाओं से सीधे जोड़ता है।',
    verifiedContacts: 'सत्यापित संपर्क',
    verifiedContactsDescription: '100% सत्यापित आपातकालीन सेवा नंबर।',
    nearbyServices: 'नज़दीकी सेवाएं',
    withinRadius: '50 किमी. के दायरे में',
    locatingYou: 'आपको ढूंढ रहे हैं...',
    fetchingNearbyHelp: 'निकटतम सहायता लाया जा रहा है...',
    noServicesFound: 'इस क्षेत्र में कोई सेवाएं नहीं मिलीं।',
    all: 'सभी',
    hospital: 'अस्पताल',
    traumaCenter: 'ट्रॉमा केंद्र',
    ambulance: 'एम्बुलेंस',
    policeStation: 'पुलिस थाना',
    towing: 'टोइंग',
    openNow: 'अब खुला',
    closed: 'बंद',
    call: 'कॉल',
    navigate: 'नेविगेट',
    emergency: 'आपातकाल',
    tapButtonForAssistance: 'तुरंत सहायता के लिए बटन दबाएं',
    sosActivatedAlert: 'SOS सक्रिय हो गया! आपके निर्देश निकटतम आपातकालीन केंद्र को भेजे जा रहे हैं।',
    callNearestAmbulance: 'निकटतम एम्बुलेंस को कॉल करें',
    callPolice: 'पुलिस को कॉल करें',
    shareLocation: 'स्थान साझा करें',
    contacts: 'संपर्क',
    youAreHere: 'आप यहाँ हैं',
    routePlotted: 'रूट तैयार किया गया!',
    emergencyProfile: 'आपातकालीन प्रोफ़ाइल',
    edit: 'संपादित करें',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    medicalNotes: 'चिकित्सा नोट्स',
    emergencyContacts: 'आपातकालीन संपर्क',
    bloodGroup: 'ब्लड ग्रुप:',
    noInternetTitle: 'इंटरनेट कनेक्शन नहीं है',
    noInternetText: 'चिंता न करें। आप अभी भी अपने अंतिम ज्ञात स्थान से निकटतम आपातकालीन संपर्कों तक पहुँच सकते हैं।',
    nationalEmergencyNumbers: 'राष्ट्रीय आपातकालीन नंबर',
    allEmergencies: 'सभी आपातकालीन',
    police: 'पुलिस',
    ambulanceLabel: 'एम्बुलेंस',
    serviceManagement: 'सेवा प्रबंधन',
    adminDescription: 'यह डैशबोर्ड सिस्टम प्रशासकों को आपातकालीन सेवा स्थानों को डेटाबेस में जोड़ने, सत्यापित करने और अपडेट करने की अनुमति देता है।',
    signInAsAdmin: 'एडमिन के रूप में साइन इन करें',
    callService: 'कॉल',
    openNowStatus: 'अब खुला',
    closedStatus: 'बंद',
    userProfileNamePlaceholder: 'नाम',
    contactNamePlaceholder: 'संपर्क नाम',
    phoneNumberPlaceholder: 'फोन नंबर',
  },
  ml: {
    navNearby: 'ചെരുവുകൾ',
    navMap: 'മ карта',
    navSOS: 'SOS',
    navOffline: 'ഓഫ്‌ലൈൻ',
    navProfile: 'പ്രൊഫൈൽ',
    navAdmin: 'അഡ്മിൻ',
    emergencyHelpTitle: 'അപകടസാഹായ്യം,\nനിനക്ക് ആവശ്യമുള്ളപ്പോൾ.',
    heroSubtitle: 'ഒരു ടാപ്പിൽ അടുത്ത തുരുകച്ചെവിയ কেন্দ্রങ്ങൾ, ആംബുലൻസ്, പോലീസ്, ടോവിംഗ് സേവനങ്ങൾ ഉടൻ കണ്ടെത്തൂ.',
    getHelpNow: 'ഇപ്പോൾ സഹായം നേടൂ',
    whyTrustTitle: 'RoadSOS-നെ എന്തുകൊണ്ട് വിശ്വസിക്കണം?',
    fastResponse: 'വേഗം പ്രതികരണം',
    fastResponseDescription: 'നിങ്ങളെ അടുത്തുള്ള ലഭ്യമായ സേവനങ്ങളോട് നേരിട്ട് ബന്ധിപ്പിക്കുന്നു.',
    verifiedContacts: 'സ്ഥിരീകരിച്ച ബന്ധങ്ങൾ',
    verifiedContactsDescription: '100% സ്ഥിരീകരിച്ച അടിയന്തര സേവന നമ്പറുകൾ.',
    nearbyServices: 'നേരത്തെ സേവനങ്ങൾ',
    withinRadius: '50 കിലോമീറ്റർ പരിധിയിൽ',
    locatingYou: 'നിനറെ കണ്ടെത്തുന്നു...',
    fetchingNearbyHelp: 'അടുത്ത സഹായം ലഭ്യമാക്കുന്നു...',
    noServicesFound: 'ഈ പ്രദേശത്ത് സേവനങ്ങൾ കണ്ടില്ല.',
    all: 'എല്ലാം',
    hospital: 'ഹോസ്പിറ്റൽ',
    traumaCenter: 'ട്രോമ സെന്റർ',
    ambulance: 'ആംബുലൻസ്',
    policeStation: 'പോലീസ് സ്റ്റേഷൻ',
    towing: 'ടോവിംഗ്',
    openNow: 'ഇപ്പോൾ തുറന്നു',
    closed: 'പൂട്ടിയിട്ടിരിക്കുന്നു',
    call: 'কল',
    navigate: 'നാവിഗേറ്റ്',
    emergency: 'അപകടസാഹായ്യം',
    tapButtonForAssistance: 'തൽക്ഷണം സഹായത്തിന് ബട്ടൺ അമർത്തുക',
    sosActivatedAlert: 'SOS സജീവമായി! നിങ്ങളുടെ കോഓർഡിനേറ്റുകൾ അടുത്ത അടിയന്തര കേന്ദ്രത്തിലേക്ക് അയയ്ക്കുന്നു.',
    callNearestAmbulance: 'ഏറ്റവും അടുത്ത ആംബുലൻസിനോട് വിളിക്കുക',
    callPolice: 'പോലീസിനെ വിളിക്കുക',
    shareLocation: 'സ്ഥലം പങ്കിടുക',
    contacts: 'ബന്ധങ്ങൾ',
    youAreHere: 'നിങ്ങൾ ഇവിടെ തന്നെയാണ്',
    routePlotted: 'പാത രേഖപ്പെടുത്തിയിട്ടുണ്ട്!',
    emergencyProfile: 'അപകട പ്രൊഫൈൽ',
    edit: 'എഡിറ്റ്',
    cancel: 'റദ്ദാക്കുക',
    save: 'സേവ്',
    medicalNotes: 'മെഡിക്കൽ കുറിപ്പുകൾ',
    emergencyContacts: 'അപകട ബന്ധങ്ങൾ',
    bloodGroup: 'രക്ത ഗ്രൂപ്പ്:',
    noInternetTitle: 'ഇന്റർനെറ്റ് കണക്ഷൻ ഇല്ല',
    noInternetText: 'ആശങ്കപ്പെടേണ്ട. നിങ്ങളുടെ അവസാനമായി അറിയപ്പെട്ട സ്ഥലം വഴി നീ പ്രാദേശിക അടിയന്തര ബന്ധങ്ങളിലേക്ക് എത്താം.',
    nationalEmergencyNumbers: 'ദേശീയ അടിയന്തര നമ്പറുകൾ',
    allEmergencies: 'എല്ലാ അടിയന്തരങ്ങളും',
    police: 'പോലീസ്',
    ambulanceLabel: 'ആംബുലൻസ്',
    serviceManagement: 'സേവ മാനേജ്‌മെന്റ്',
    adminDescription: 'ഈ ഡാഷ്ബോർഡ് സിസ്റ്റം അഡ്മിനിസ്റ്റ്രേറ്റർമാർക്ക് അടിയന്തര സേവന സ്ഥാനങ്ങൾ ഡേറ്റാബേസിൽ ചേർക്കാനും, സ്ഥിരീകരിക്കാനും, അപ്‌ഡേറ്റ് ചെയ്യാനും സഹായിക്കുന്നു.',
    signInAsAdmin: 'അഡ്മിൻ എന്ന നിലയിൽ സൈൻ ഇൻ ചെയ്യുക',
    callService: 'കോൾ',
    openNowStatus: 'ഇപ്പോൾ തുറന്നു',
    closedStatus: 'പൂട്ടിയിട്ടിരിക്കുന്നു',
    userProfileNamePlaceholder: 'പേര്',
    contactNamePlaceholder: 'ബന്ധത്തിന്റെ പേര്',
    phoneNumberPlaceholder: 'ഫോൺ നമ്പർ',
  },
  ur: {
    navNearby: 'قریب',
    navMap: 'نقشہ',
    navSOS: 'SOS',
    navOffline: 'آف لائن',
    navProfile: 'پروفائل',
    navAdmin: 'ایڈمن',
    emergencyHelpTitle: 'ہنگامی مدد،\nجب آپ کو ضرورت ہو۔',
    heroSubtitle: 'ایک ٹپ میں نزدیک ترین ٹروما سینٹر، ایمبولینس، پولیس، اور ٹوئنگ خدمات تلاش کریں۔',
    getHelpNow: 'اب مدد حاصل کریں',
    whyTrustTitle: 'RoadSOS پر کیوں اعتماد کریں؟',
    fastResponse: 'فوری جواب',
    fastResponseDescription: 'آپ کو سب سے قریب دستیاب خدمات سے براہ راست جوڑتا ہے۔',
    verifiedContacts: 'تصدیق شدہ رابطے',
    verifiedContactsDescription: '100% تصدیق شدہ ہنگامی خدمت نمبر۔',
    nearbyServices: 'قریب کے خدمات',
    withinRadius: '50 کلومیٹر کی حدود میں',
    locatingYou: 'آپ کو تلاش کر رہا ہے...',
    fetchingNearbyHelp: 'قریب کی مدد لائی جارہی ہے...',
    noServicesFound: 'اس علاقے میں کوئی خدمات نہیں ملی۔',
    all: 'تمام',
    hospital: 'ہسپتال',
    traumaCenter: 'ٹراما سنٹر',
    ambulance: 'ایمبولینس',
    policeStation: 'پولیس اسٹیشن',
    towing: 'ٹوئنگ',
    openNow: 'ابھی کھلا',
    closed: 'بند',
    call: 'کال کریں',
    navigate: 'نیویگیٹ',
    emergency: 'ہنگامی صورتحال',
    tapButtonForAssistance: 'فوری مدد کے لیے بٹن دبائیں',
    sosActivatedAlert: 'SOS فعال ہوگیا! آپ کے کوآرڈینیٹ نزدیک ترین ہنگامی مرکز کو بھیجے جارہے ہیں۔',
    callNearestAmbulance: 'قریب ترین ایمبولینس کو کال کریں',
    callPolice: 'پولیس کو کال کریں',
    shareLocation: 'مقام شیئر کریں',
    contacts: 'رابطے',
    youAreHere: 'آپ یہاں ہیں',
    routePlotted: 'راستہ دکھایا گیا!',
    emergencyProfile: 'ہنگامی پروفائل',
    edit: 'ترمیم کریں',
    cancel: 'منسوخ کریں',
    save: 'محفوظ کریں',
    medicalNotes: 'طبی نوٹس',
    emergencyContacts: 'ہنگامی رابطے',
    bloodGroup: 'بلڈ گروپ:',
    noInternetTitle: 'انٹرنیٹ کنکشن دستیاب نہیں',
    noInternetText: 'پریشان نہ ہوں۔ آپ اب بھی اپنے آخری معلوم مقام سے قریب ترین ہنگامی رابطوں تک پہنچ سکتے ہیں۔',
    nationalEmergencyNumbers: 'قومی ہنگامی نمبر',
    allEmergencies: 'تمام ہنگامی',
    police: 'پولیس',
    ambulanceLabel: 'ایمبولینس',
    serviceManagement: 'سروس مینجمنٹ',
    adminDescription: 'یہ ڈیش بورڈ نظام ایڈمنسٹریٹرز کو ہنگامی سروس مقامات کو ڈیٹا بیس میں شامل، تصدیق، اور اپ ڈیٹ کرنے کی اجازت دیتا ہے۔',
    signInAsAdmin: 'ایڈمن کے طور پر سائن ان کریں',
    callService: 'کال کریں',
    openNowStatus: 'ابھی کھلا',
    closedStatus: 'بند',
    userProfileNamePlaceholder: 'نام',
    contactNamePlaceholder: 'رابطے کا نام',
    phoneNumberPlaceholder: 'فون نمبر',
  },
  ks: {
    navNearby: 'ژٔیٔتھ',
    navMap: 'نقشہ',
    navSOS: 'SOS',
    navOffline: 'آف لائن',
    navProfile: 'پروفائل',
    navAdmin: 'ایڈمین',
    emergencyHelpTitle: 'ایمرجنسی مدد،\nژٔے تہند ضرورت آے۔',
    heroSubtitle: 'یک ٹِٔپ ہِند نزدِیک تھرامہ سینٹر، ایمبولینس، پولیس، تہ ٹُوینگ خدمات ژٔیٔہ تلاش کرنُ.',
    getHelpNow: 'ہنز مدد حاصل کر',
    whyTrustTitle: 'RoadSOS پِر کیوں اعتبار؟',
    fastResponse: 'سُتَر جواب',
    fastResponseDescription: 'تُہند نزدیک دستیاب خدمات سیتھ سیدھا جوڑتھ.',
    verifiedContacts: 'ثابت کردہ رابطے',
    verifiedContactsDescription: '100% ثابت کردہ ایمرجنسی خدمات نمبر.',
    nearbyServices: 'نزدیک خدمات',
    withinRadius: '50 کلومیٹر دائرہ ہند',
    locatingYou: 'تُہند تلاش کران...',
    fetchingNearbyHelp: 'نزدیک مدد لاوُن پَتھ...',
    noServicesFound: 'ایہہ علاقے تُند خدمات نہ ملیون.',
    all: 'سَب',
    hospital: 'ہسپتال',
    traumaCenter: 'ٹراما سنٹر',
    ambulance: 'ایمبولینس',
    policeStation: 'پولیس اسٹیشن',
    towing: 'ٹوینگ',
    openNow: 'ہنز کھلہ',
    closed: 'بند',
    call: 'کال کر',
    navigate: 'رستہ',
    emergency: 'ایمرجنسی',
    tapButtonForAssistance: 'فوری مدد کارہِ گُچھ پتن بٹن چھیڑن',
    sosActivatedAlert: 'SOS فعال ہند! تُہند کوآرڈینیٹ نزدِیک ایمرجنسی سنٹر کڑ بھیجن پئے۔',
    callNearestAmbulance: 'نزدیک ایمبولینس کڑ کال کر',
    callPolice: 'پولیس کڑ کال کر',
    shareLocation: 'مقام ونڈن',
    contacts: 'رابطے',
    youAreHere: 'تُہو اِتھہ ہی',
    routePlotted: 'رستہ نقشہ وِچ ٹھونڈا گیا!',
    emergencyProfile: 'ایمرجنسی پروفائل',
    edit: 'ترمیم',
    cancel: 'منسوخ',
    save: 'محفوظ',
    medicalNotes: 'طبی نوٹس',
    emergencyContacts: 'ایمرجنسی رابطے',
    bloodGroup: 'بلڈ گروپ:',
    noInternetTitle: 'انٹرنیٹ کنکشن نہ آہے',
    noInternetText: 'فکر نہ کر. تُہو ہنز اپنے آخری پتو سیتھ نزدیک ایمرجنسی رابطے حاصل کر سکتھے.',
    nationalEmergencyNumbers: 'قومی ایمرجنسی نمبر',
    allEmergencies: 'سَب ایمرجنسی',
    police: 'پولیس',
    ambulanceLabel: 'ایمبولینس',
    serviceManagement: 'سروس انتظام',
    adminDescription: 'ایہہ ڈیشبورڈ نظام نظم اداری کڑ اجازت دیندہ کہ ایمرجنسی سروس مقام ڈاٹابیس وچ شامل، ثابت، تہ اپ ڈیٹ کرن.',
    signInAsAdmin: 'ایڈمین وضع وچ سائن ان کر',
    callService: 'کال کر',
    openNowStatus: 'ہنز کھلہ',
    closedStatus: 'بند',
    userProfileNamePlaceholder: 'ناؤ',
    contactNamePlaceholder: 'رابطے ہند ناؤ',
    phoneNumberPlaceholder: 'فون نمبر',
  },
  kn: {
    navNearby: 'ಸದೃಶ',
    navMap: 'ನಕ್ಷೆ',
    navSOS: 'SOS',
    navOffline: 'ಆಫ್‌ಲೈನ್',
    navProfile: 'ಪ್ರೊಫೈಲ್',
    navAdmin: 'ಆಡ್ಮಿನ್',
    emergencyHelpTitle: 'ತುರ್ತು ಸಹಾಯ,\nನೀವು ಬೇಕಾದಾಗಲೇ.',
    heroSubtitle: 'ಒಂದು ಟ್ಯಾಪ್‌ನಿಂದ ಸಮೀಪದ ಟ್ರಾಮಾ ಸೆಂಟರ್‌ಗಳು, ಆಂಬ್ಯುಲೆನ್ಸ್‌ಗಳು, ಪೊಲೀಸ್ ಮತ್ತು ಟೋವಿಂಗ್ ಸೇವೆಗಳನ್ನು ತಕ್ಷಣವೇ ಹುಡುಕಿ.',
    getHelpNow: 'ಈಗ ಸಹಾಯ ಪಡೆಯಿರಿ',
    whyTrustTitle: 'RoadSOS ಅನ್ನು ಏಕೆ ನಂಬಬೇಕು?',
    fastResponse: 'ವೇಗದ ಪ್ರತಿಕ್ರಿಯೆ',
    fastResponseDescription: 'ನಿಮಗೆ ಅತಿ ಸಮೀಪದ ಲಭ್ಯವಿರುವ ಸೇವೆಗಳನ್ನು ನೇರವಾಗಿ ಸಂಪರ್ಕಿಸುತ್ತದೆ.',
    verifiedContacts: 'ಅನುಮೋದಿತ ಸಂಪರ್ಕಗಳು',
    verifiedContactsDescription: '100% ಪರಿಶೀಲಿತ ತುರ್ತು ಸೇವಾ ಸಂಖ್ಯೆಗಳು.',
    nearbyServices: 'ಅೊಗ್ಗಿ ಸೇವೆಗಳು',
    withinRadius: '50 ಕಿಮೀ ವ್ಯಾಪ್ತಿಯಲ್ಲಿ',
    locatingYou: 'ನಿಮ್ಮನ್ನು ಹುಡುಕುತ್ತಿದೆ...',
    fetchingNearbyHelp: 'ಸಮೀಪದ ಸಹಾಯವನ್ನು ತರಿಸಲಾಗುತ್ತಿದೆ...',
    noServicesFound: 'ಈ ವಲಯದಲ್ಲಿ ಯಾವುದೇ ಸೇವೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
    all: 'ಎಲ್ಲ',
    hospital: 'ಆಸ್ಪತ್ರೆ',
    traumaCenter: 'ಟ್ರಾಮಾ ಕೇಂದ್ರ',
    ambulance: 'ಆಂಬ್ಯುಲೆನ್ಸ್',
    policeStation: 'ಪೊಲೀಸ್ ಠಾಣೆ',
    towing: 'ಟೋವಿಂಗ್',
    openNow: 'ಈಗ ತೆರೆಯಲಾಗಿದೆ',
    closed: 'ಮುಚ್ಚಿದೆ',
    call: 'ಕಾಲ್ ಮಾಡಿ',
    navigate: 'ನಾವುಗೆಟ್',
    emergency: 'ತುರ್ತು',
    tapButtonForAssistance: 'ತ್ವರಿತ ಸಹಾಯಕ್ಕೆ ಬಟನ್ ಒತ್ತಿ',
    sosActivatedAlert: 'SOS ಸಕ್ರಿಯಗೊಳ್ಳಿತು! ನಿಮ್ಮ ಸ್ಥಿತಿಚಿತ್ರಗಳು ಸಮೀಪದ ತುರ್ತು ಕೇಂದ್ರಕ್ಕೆ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ.',
    callNearestAmbulance: 'ಸಮೀಪದ ಆಂಬ್ಯುಲೆನ್ಸ್‍ನ್ನು ಕರೆ ಮಾಡಿ',
    callPolice: 'ಪೊಲೀಸ್‍ನ್ನು ಕರೆ ಮಾಡಿ',
    shareLocation: 'ಸ್ಥಳ ಹಂಚಿಕೊಳ್ಳಿ',
    contacts: 'ಸಂಪರ್ಕಗಳು',
    youAreHere: 'ನೀವು ಇಲ್ಲಿ ಇದ್ದೀರಿ',
    routePlotted: 'ರಸ್ತೆ ಚಿತ್ರಿಸಲಾಗಿದೆ!',
    emergencyProfile: 'ತುರ್ತು ಪ್ರೊಫೈಲ್',
    edit: 'ತಿದ್ದುಪಡಿಸು',
    cancel: 'ರದ್ದುಮಾಡಿ',
    save: 'ಉಳಿಸಿ',
    medicalNotes: 'ವೈದ್ಯಕೀಯ ಟಿಪ್ಪಣಿಗಳು',
    emergencyContacts: 'ತುರ್ತು ಸಂಪರ್ಕಗಳು',
    bloodGroup: 'ರಕ್ತ ಗುಂಪು:',
    noInternetTitle: 'ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕ ಇಲ್ಲ',
    noInternetText: 'ಚಿಂತೆ ಮಾಡಬೇಡ. ನೀವು ಇನ್ನೂ ನಿಮ್ಮ ಕೊನೆಯ ಕಾಣಿಸಿದ ಸ್ಥಳದಿಂದ ಸಮೀಪದ ತುರ್ತು ಸಂಪರ್ಕಗಳಿಗೆ ಹೋಲಬಹುದು.',
    nationalEmergencyNumbers: 'ರಾಷ್ಟ್ರೀಯ ತುರ್ತು ಸಂಖ್ಯೆಗಳು',
    allEmergencies: 'ಎಲ್ಲಾ ತುರ್ತುಗಳು',
    police: 'ಪೊಲೀಸ್',
    ambulanceLabel: 'ಆಂಬ್ಯುಲೆನ್ಸ್',
    serviceManagement: 'ಸೇವಾ ನಿರ್ವಹಣೆ',
    adminDescription: 'ಈ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ವ್ಯವಸ್ಥೆಯು ನಿರ್ವಹಕರಿಗೆ ತುರ್ತು ಸೇವಾ ಸ್ಥಳಗಳನ್ನು ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ಸೇರಿಸಲು, ಪರಿಶೀಲಿಸಲು ಮತ್ತು ನವೀಕರಿಸಲು ಅನುಮತಿಸುತ್ತದೆ.',
    signInAsAdmin: 'ಆಡ್ಮಿನ್ ಆಗಿ ಲಾಗಿನ್ ಮಾಡಿ',
    callService: 'ಕಾಲ್ ಮಾಡಿ',
    openNowStatus: 'ಈಗ ತೆರೆಯಲಾಗಿದೆ',
    closedStatus: 'ಮುಚ್ಚಿದೆ',
    userProfileNamePlaceholder: 'ಹೆಸರು',
    contactNamePlaceholder: 'ಸಂಪರ್ಕದ ಹೆಸರು',
    phoneNumberPlaceholder: 'ಫೋನ್ ಸಂಖ್ಯೆ',
  },
  bn: {
    navNearby: 'নিকটে',
    navMap: 'মানচিত্র',
    navSOS: 'এসওএস',
    navOffline: 'অফলাইন',
    navProfile: 'প্রোফাইল',
    navAdmin: 'অ্যাডমিন',
    emergencyHelpTitle: 'জরুরি সহায়তা,\nযখন আপনার প্রয়োজন হয়।',
    heroSubtitle: 'একটি ট্যাপে নিকটতম ট্রমা কেন্দ্র, অ্যাম্বুলেন্স, পুলিশ এবং টোয়িং পরিষেবা খুঁজুন।',
    getHelpNow: 'এখন সাহায্য নিন',
    whyTrustTitle: 'RoadSOS-এ কেন বিশ্বাস?',
    fastResponse: 'দ্রুত প্রতিক্রিয়া',
    fastResponseDescription: 'আপনাকে নিকটতম উপলব্ধ পরিষেবার সাথে সরাসরি সংযুক্ত করে।',
    verifiedContacts: 'যাচাইকৃত যোগাযোগ',
    verifiedContactsDescription: '100% যাচাইকৃত জরুরি সেবা নম্বর।',
    nearbyServices: 'নিকটবর্তী পরিষেবা',
    withinRadius: '৫০ কিমি ব্যাসার্ধে',
    locatingYou: 'আপনাকে খুঁজছে...',
    fetchingNearbyHelp: 'নিকটবর্তী সাহায্য আনছে...',
    noServicesFound: 'এই এলাকায় কোনও পরিষেবা পাওয়া যায়নি।',
    all: 'সব',
    hospital: 'হাসপাতাল',
    traumaCenter: 'ট্রমা কেন্দ্র',
    ambulance: 'অ্যাম্বুল্যান্স',
    policeStation: 'পুলিশ স্টেশন',
    towing: 'টোয়িং',
    openNow: 'এখন খোলা',
    closed: 'বন্ধ',
    call: 'কল',
    navigate: 'নেভিগেট',
    emergency: 'জরুরি',
    tapButtonForAssistance: 'তাৎক্ষণিক সহায়তার জন্য বোতাম টিপুন',
    sosActivatedAlert: 'SOS সক্রিয় হয়েছে! আপনার কোঅর্ডিনেট নিকটতম জরুরি কেন্দ্রে পাঠানো হচ্ছে।',
    callNearestAmbulance: 'নিকটতম অ্যাম্বুল্যান্সে কল করুন',
    callPolice: 'পুলিশে কল করুন',
    shareLocation: 'অবস্থান শেয়ার করুন',
    contacts: 'যোগাযোগ',
    youAreHere: 'তুমি এখানে আছো',
    routePlotted: 'রুট চিত্রিত হয়েছে!',
    emergencyProfile: 'জরুরি প্রোফাইল',
    edit: 'সম্পাদনা',
    cancel: 'বাতিল',
    save: 'সংরক্ষণ',
    medicalNotes: 'চিকিৎসা নোট',
    emergencyContacts: 'জরুরি যোগাযোগ',
    bloodGroup: 'রক্তের গ্রুপ:',
    noInternetTitle: 'ইন্টারনেট সংযোগ নেই',
    noInternetText: 'উদ্বিগ্ন হবেন না। আপনি এখনও আপনার শেষ জানা অবস্থান থেকে নিকটতম জরুরি যোগাযোগগুলিতে পৌঁছাতে পারেন।',
    nationalEmergencyNumbers: 'জাতীয় জরুরি নম্বর',
    allEmergencies: 'সকল জরুরি',
    police: 'পুলিশ',
    ambulanceLabel: 'অ্যাম্বুল্যান্স',
    serviceManagement: 'পরিষেবা পরিচালনা',
    adminDescription: 'এই ড্যাশবোর্ড সিস্টেম প্রশাসকদের জরুরি সেবা স্থাপনাগুলি ডাটাবেসে যোগ, যাচাই এবং আপডেট করতে দেয়।',
    signInAsAdmin: 'অ্যাডমিন হিসাবে সাইন ইন করুন',
    callService: 'কল',
    openNowStatus: 'এখন খোলা',
    closedStatus: 'বন্ধ',
    userProfileNamePlaceholder: 'নাম',
    contactNamePlaceholder: 'যোগাযোগের নাম',
    phoneNumberPlaceholder: 'ফোন নম্বর',
  },
  or: {
    navNearby: 'ନିକଟରେ',
    navMap: 'ନକ୍ସା',
    navSOS: 'SOS',
    navOffline: 'ଅଫ୍ଲାଇନ୍',
    navProfile: 'ପ୍ରୋଫାଇଲ୍',
    navAdmin: 'ଆଡମିନ୍',
    emergencyHelpTitle: 'ଏମର୍ଜେନ୍ସି ସହାୟତା,\nଆପଣଙ୍କୁ ଆବଶ୍ୟକ ହେଲେ।',
    heroSubtitle: 'ଏକ ଟ୍ୟାପ୍‌ରେ ସମୀପର ହେବାକୁ ଥ୍ରୋମା କେନ୍ଦ୍ର, ଆମ୍ବୁଲେନ୍ସ, ପୋଲିସ୍ ଏବଂ ଟୋଇଂ ସେବାଗୁଡିକୁ ତୁରନ୍ତ ଖୋଜନ୍ତୁ।',
    getHelpNow: 'ଏବେ ସହାୟତା ନିଅନ୍ତୁ',
    whyTrustTitle: 'RoadSOS ଉପରେ କାହିଁକି ଭରସା?',
    fastResponse: 'ଦ୍ରୁତ ପ୍ରତିକ୍ରିୟା',
    fastResponseDescription: 'ଆପଣଙ୍କୁ ନିକଟମ ଉପଲବ୍ଧ ସେବାର ସହିତ ସିଧା ସଂଯୋଗ କରେ।',
    verifiedContacts: 'ଯାଚିତ ସଂପର୍କ',
    verifiedContactsDescription: '100% ଯାଚିତ ଆପତ୍କାଳୀନ ସେବା ସଂଖ୍ୟା।',
    nearbyServices: 'ନିକଟର ସେବା',
    withinRadius: '50 କିଲୋମିଟର ରେଡିଅସ ମଧ୍ୟରେ',
    locatingYou: 'ଆପଣଙ୍କୁ ଖୋଜୁଛି...',
    fetchingNearbyHelp: 'ନିକଟର ସାହାଯ୍ୟ ଆଣୁଛି...',
    noServicesFound: 'ଏହି ଅଞ୍ଚଳରେ କୌଣସି ସେବା ମିଳିଲା ନାହିଁ।',
    all: 'ସବୁ',
    hospital: 'ହସ୍ପିଟାଲ୍',
    traumaCenter: 'ଟ୍ରମା କେନ୍ଦ୍ର',
    ambulance: 'ଆମ୍ବୁଲେନ୍ସ୍',
    policeStation: 'ପୋଲିସ୍ ସ୍ଟେସନ୍',
    towing: 'ଟୋୱିଂ',
    openNow: 'ବର୍ତ୍ତମାନ ଖୋଲା',
    closed: 'ବନ୍ଦ',
    call: 'କଲ୍ କରନ୍ତୁ',
    navigate: 'ନେଭିଗେଟ୍',
    emergency: 'ଆପତ୍କାଳୀନ',
    tapButtonForAssistance: 'ତତ୍କ୍ଷଣାତ ସହାୟତା ପାଇଁ ବଟନ ଦବାନ୍ତୁ',
    sosActivatedAlert: 'SOS ସକ୍ରିୟ ହୋଇଛି! ଆପଣଙ୍କର ସମନ୍ତ ନିକଟସ୍ଥ ଆପତ୍କାଳୀନ କେନ୍ଦ୍ରକୁ ପଠାଯାଉଛି।',
    callNearestAmbulance: 'ନିକଟମ ଆମ୍ବୁଲେନ୍ସ୍ କୁ କଲ୍ କରନ୍ତୁ',
    callPolice: 'ପୋଲିସ୍ କୁ କଲ୍ କରନ୍ତୁ',
    shareLocation: 'ଅବସ୍ଥାନ ସେୟାର୍ କରନ୍ତୁ',
    contacts: 'ସମ୍ପର୍କ',
    youAreHere: 'ଆପଣ ଏଠାରେ ଅଛନ୍ତି',
    routePlotted: 'ପଥ ଚିତ୍ରିତ ହୋଇଛି!',
    emergencyProfile: 'ଆପତ୍କାଳୀନ ପ୍ରୋଫାଇଲ୍',
    edit: 'ସମ୍ପାଦନା',
    cancel: 'ବାତିଲ୍ କରନ୍ତୁ',
    save: 'ସଞ୍ଚୟ',
    medicalNotes: 'ଚିକିତ୍ସା ସୂଚନା',
    emergencyContacts: 'ଆପତ୍କାଳୀନ ସମ୍ପର୍କଗୁଡିକ',
    bloodGroup: 'ରକ୍ତ ଗୋଷ୍ଠୀ:',
    noInternetTitle: 'ଇଣ୍ଟରନେଟ୍ ସଂଯୋଗ ନାହିଁ',
    noInternetText: 'ଚିନ୍ତା କରନ୍ତୁ ନାହିଁ. ଆପଣ ଆଉ ମଧ୍ୟ ଆପଣଙ୍କର ଶେଷ ଜଣା ଅବସ୍ଥାନରୁ ନିକଟର ଆପତ୍କାଳୀନ ସମ୍ପର୍କଗୁଡିକୁ ପହଞ୍ଚିପାରିବେ।',
    nationalEmergencyNumbers: 'ଜାତୀୟ ଆପତ୍କାଳୀନ ସଂଖ୍ୟାଗୁଡିକ',
    allEmergencies: 'ସମସ୍ତ ଆପତ୍କାଳୀନ',
    police: 'ପୋଲିସ୍',
    ambulanceLabel: 'ଆମ୍ବୁଲେନ୍ସ୍',
    serviceManagement: 'ସେବା ପ୍ରବନ୍ଧନ',
    adminDescription: 'ଏହି ଡ୍ୟାସ୍ ବୋର୍ଡ୍ ପ୍ରଣାଳୀ ପ୍ରଶାସକଙ୍କୁ ଆପତ୍କାଳୀନ ସେବା ସ୍ଥାନଗୁଡିକୁ ଡାଟାବେସ୍‌ରେ ଯୋଗ, ପରିଶୋଧନ ଏବଂ ଅଦ୍ୟତନ କରିବାର ସୁଯୋଗ ଦେଇଥାଏ।',
    signInAsAdmin: 'ଆଡମିନ୍ ଭାବେ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    callService: 'କଲ୍ କରନ୍ତୁ',
    openNowStatus: 'ବର୍ତ୍ତମାନ ଖୋଲା',
    closedStatus: 'ବନ୍ଦ',
    userProfileNamePlaceholder: 'ନାମ',
    contactNamePlaceholder: 'ସମ୍ପର୍କର ନାମ',
    phoneNumberPlaceholder: 'ଫୋନ୍ ନମ୍ବର',
  },
  mr: {
    navNearby: 'जवळ',
    navMap: 'नकाशा',
    navSOS: 'SOS',
    navOffline: 'ऑफलाइन',
    navProfile: 'प्रोफाइल',
    navAdmin: 'अ‍ॅडमिन',
    emergencyHelpTitle: 'आपत्कालीन मदत,\nज्यावेळी तुम्हाला हवी तेव्हा.',
    heroSubtitle: 'एक टॅपमध्ये जवळचे ट्रॉमा केंद्र, अम्ब्युलन्स, पोलिस आणि टोविंग सेवा शोधा.',
    getHelpNow: 'आत्ता मदत घ्या',
    whyTrustTitle: 'RoadSOS वर का विश्वास?',
    fastResponse: 'जलद प्रतिसाद',
    fastResponseDescription: 'तुम्हाला नजीकच्या उपलब्ध सेवांशी थेट जोडते.',
    verifiedContacts: 'तपासलेले संपर्क',
    verifiedContactsDescription: '100% तपासलेले आपत्कालीन सेवा नंबर.',
    nearbyServices: 'जवळच्या सेवा',
    withinRadius: '50 किमी परिघात',
    locatingYou: 'तुम्हाला शोधत आहे...',
    fetchingNearbyHelp: 'जवळचे मदत आणले जात आहे...',
    noServicesFound: 'या भागात कोणतीही सेवा सापडली नाही.',
    all: 'सर्व',
    hospital: 'रुग्णालय',
    traumaCenter: 'ट्रॉमा केंद्र',
    ambulance: 'अँब्युलन्स',
    policeStation: 'पोलीस स्टेशन',
    towing: 'टोविंग',
    openNow: 'आता उघडे आहे',
    closed: 'बंद',
    call: 'कॉल करा',
    navigate: 'नॅव्हिगेट',
    emergency: 'आपत्कालीन',
    tapButtonForAssistance: 'ताबडतोब मदतीसाठी बटण दाबा',
    sosActivatedAlert: 'SOS सक्रिय केले! तुमचे निर्देश जवळच्या आपत्कालीन केंद्राला पाठवले जात आहेत.',
    callNearestAmbulance: 'जवळच्या अँब्युलन्सला कॉल करा',
    callPolice: 'पोलीसला कॉल करा',
    shareLocation: 'स्थान सामायिक करा',
    contacts: 'संपर्क',
    youAreHere: 'तू इथे आहेस',
    routePlotted: 'मार्ग आखला गेला!',
    emergencyProfile: 'आपत्कालीन प्रोफाइल',
    edit: 'संपादित करा',
    cancel: 'रद्द करा',
    save: 'जतन करा',
    medicalNotes: 'वैद्यकीय टिपण्या',
    emergencyContacts: 'आपत्कालीन संपर्क',
    bloodGroup: 'रक्त गट:',
    noInternetTitle: 'इंटरनेट कनेक्शन नाही',
    noInternetText: 'काळजी करू नका. तुम्ही अजूनही तुमच्या शेवटच्या माहित असलेल्या ठिकाणाहून जवळच्या आपत्कालीन संपर्कांपर्यंत पोहोचू शकता.',
    nationalEmergencyNumbers: 'राष्ट्रीय आपत्कालीन क्रमांक',
    allEmergencies: 'सर्व आपत्कालीन',
    police: 'पोलीस',
    ambulanceLabel: 'अँब्युलन्स',
    serviceManagement: 'सेवा व्यवस्थापन',
    adminDescription: 'हा डॅशबोर्ड सिस्टम प्रशासकांना आपत्कालीन सेवा स्थान डेटाबेसमध्ये जोडण्याची, सत्यापित करण्याची आणि अद्ययावत करण्याची परवानगी देते.',
    signInAsAdmin: 'अ‍ॅडमिन म्हणून साइन इन करा',
    callService: 'कॉल करा',
    openNowStatus: 'आता उघडे आहे',
    closedStatus: 'बंद',
    userProfileNamePlaceholder: 'नाव',
    contactNamePlaceholder: 'संपर्क नाव',
    phoneNumberPlaceholder: 'फोन नंबर',
  },
  gu: {
    navNearby: 'લગત્યે',
    navMap: 'નકશો',
    navSOS: 'SOS',
    navOffline: 'ઓફલાઈન',
    navProfile: 'પ્રોફાઇલ',
    navAdmin: 'એડમિન',
    emergencyHelpTitle: 'જરૂરી помощь,\nજ્યારે તમને તેની જરૂર પડે છે.',
    heroSubtitle: 'એક ટૅપમાં નિકટમ ટ્રૌમા સેન્ટર, એમ્બ્યુલન્સ, પોલીસ અને ટોઇંગ સેવાઓ શોધો.',
    getHelpNow: 'હવે મદદ મેળવો',
    whyTrustTitle: 'RoadSOS પર કેમ વિશ્વાસ?',
    fastResponse: 'ઝડપી પ્રતિસાદ',
    fastResponseDescription: 'તમને સૌથી નજીકની પ્રાપ્ય સેવાઓ સાથે સીધા જોડે છે.',
    verifiedContacts: 'તપાસ કરેલ સંપર્કો',
    verifiedContactsDescription: '100% તપાસ કરેલ એમર્જન્સી સેવા નંબર.',
    nearbyServices: 'નિકટની સેવાઓ',
    withinRadius: '50 કિમી વિસ્તારમાં',
    locatingYou: 'તમને શોધી રહી છે...',
    fetchingNearbyHelp: 'નિકટની સહાય લાવી રહ્યું છે...',
    noServicesFound: 'આ વિસ્તારમાં કોઈ સેવા મળી નથી.',
    all: 'બધા',
    hospital: 'હોસ્પિટલ',
    traumaCenter: 'ત્રાસ દાવા કેન્દ્ર',
    ambulance: 'એમ્બ્યુલન્સ',
    policeStation: 'પોલીસ સ્ટેશન',
    towing: 'ટોઇંગ',
    openNow: 'હવે ખુલ્યું છે',
    closed: 'બંધ',
    call: 'કોલ કરો',
    navigate: 'નાવીગેટ',
    emergency: 'ઇમર્જન્સી',
    tapButtonForAssistance: 'તાત્કાલિક સહાયત માટે બટન દબાવો',
    sosActivatedAlert: 'SOS સક્રિય થયું! તમારા place આકર્ષણો નેસ્ટ ઇમર્જન્સી કેન્દ્ર પર મોકલવામાં આવી રહ્યા છે.',
    callNearestAmbulance: 'નજીકની એમ્બ્યુલન્સને કોલ કરો',
    callPolice: 'પોલીસને કોલ કરો',
    shareLocation: 'સ્થાન શેર કરો',
    contacts: 'સંપર્કો',
    youAreHere: 'તમે અહીં છો',
    routePlotted: 'રૂટ ગોઠવાયું છે!',
    emergencyProfile: 'ઇમર્જન્સી પ્રોફાઇલ',
    edit: 'સંપાદિત કરો',
    cancel: 'રદ કરો',
    save: 'સેવ કરો',
    medicalNotes: 'વૈદ્યકીય નોંધો',
    emergencyContacts: 'ઇમર્જન્સી સંપર્કો',
    bloodGroup: 'રક્ત જૂથ:',
    noInternetTitle: 'ઇન્ટરનેટ કનેક્શન નથી',
    noInternetText: 'ચિંતા ન કરો. તમે હજુ પણ તમારા છેલ્લી જાણીતું સ્થાનથી નજીકના ઇમર્જન્સી સંપર્કો સુધી પહોંચી શકો છો.',
    nationalEmergencyNumbers: 'રાષ્ટ્રીય ઇમર્ઝન્સી નંબર',
    allEmergencies: 'બધા ઇમર્જન્સી',
    police: 'પોલીસ',
    ambulanceLabel: 'એમ્બ્યુલન્સ',
    serviceManagement: 'સેવા વ્યવસ્થાપન',
    adminDescription: 'આ ડૅશબોર્ડ સિસ્ટમ પ્રબંધકોને ઇમર્જન્સી સેવા સ્થળોને ડેટાબેસમાં ઉમેરી, ચકાસી અને અપડેટ કરવાની પરવાનગી આપે છે.',
    signInAsAdmin: 'એડમિન તરીકે સાઇન ઇન કરો',
    callService: 'કોલ કરો',
    openNowStatus: 'હવે ખુલ્યું છે',
    closedStatus: 'બંધ',
    userProfileNamePlaceholder: 'નામ',
    contactNamePlaceholder: 'સંપર્કનું નામ',
    phoneNumberPlaceholder: 'ફોન નંબર',
  }
};

const LanguageContext = createContext();

const getInitialLanguage = () => {
  const saved = localStorage.getItem('roadSOS_language');
  if (saved && supportedLanguages.some((lang) => lang.code === saved)) {
    return saved;
  }
  const browserLang = navigator.language?.slice(0, 2);
  return supportedLanguages.some((lang) => lang.code === browserLang) ? browserLang : 'en';
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    localStorage.setItem('roadSOS_language', language);
  }, [language]);

  const contextValue = useMemo(() => ({
    language,
    setLanguage,
    languages: supportedLanguages,
    translations: translations[language] || translations.en,
  }), [language]);

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within LanguageProvider');
  }

  const t = (key, fallback) => {
    return context.translations[key] || fallback || key;
  };

  return {
    ...context,
    t,
  };
};
